services:

  frontend:
    container_name: angular-app
    build:
      context: ./spring-boot-microservices-angular/frontend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - gateway
    networks:
      - microservices-network
    restart: unless-stopped

  eureka:
    container_name: eureka-service
    build:
      context: ./spring-boot-microservices-angular/backend/eureka-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    restart: unless-stopped
  
  gateway:
    container_name: api-gateway-service
    build:
      context: ./spring-boot-microservices-angular/backend/api-gateway-service
    ports:
      - "8888:8090"
    depends_on:
      - eureka
    networks:
      - microservices-network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    restart: unless-stopped

  answer:
    container_name: answer-service
    build:
      context: ./spring-boot-microservices-angular/backend/answer-service
      dockerfile: dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - gateway
      - mongodb
    networks:
      - microservices-network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    restart: unless-stopped

  user-service:
    container_name: user-service
    build:
      context: ./spring-boot-microservices-angular/backend
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - gateway
      - postgres
    networks:
      - microservices-network
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/microservices_users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changeme
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: microservices_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:

networks:
  microservices-network:
    driver: bridge